spring.kafka:
  bootstrap-servers: localhost:9092

spring.cloud.stream:
  function:
    definition: odd;even;uppercase;functionRouter

  bindingRetryInterval: 1000
  defaultBinder: kafka
  kafka.binder:
    autoAddPartitions: true
    replicationFactor: 1
    minPartitionCount: 3

  kafka.streams.binder:
    brokers:  localhost:9092
    configuration:
      commit.interval.ms: 10
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.springframework.kafka.support.serializer.JsonSerde


  bindings:
    uppercase-in-0:
      destination: word-in,word-in-1
    uppercase-out-0:
      destination: word-out
    functionRouter-in-0:
      destination: router-in-1,router-in-2

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: demo

server:
  port: 18080

